# Create a 2D image array and print it

In [1]:
import numpy as np

image = np.array([
    [0,   50,  100],
    [150, 200, 255],
    [30,  80,  220]
], dtype=np.uint8)

print(image)

[[  0  50 100]
 [150 200 255]
 [ 30  80 220]]


# Inspect image properties (shape, dtype, min, max)

In [2]:
print("shape:", image.shape)
print("dtype:", image.dtype)
print("min:", image.min())
print("max:", image.max())

shape: (3, 3)
dtype: uint8
min: 0
max: 255


# Create an RGB image array and print it

In [3]:
rgb_image = np.array([
    [[255,   0,   0], [  0, 255,   0]],
    [[  0,   0, 255], [255, 255, 255]]
], dtype=np.uint8)

print(rgb_image)

[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255 255]]]


# Inspect RGB image properties

In [4]:
print("shape:", rgb_image.shape)
print("dtype:", rgb_image.dtype)
print("min:", rgb_image.min())
print("max:", rgb_image.max())

shape: (2, 2, 3)
dtype: uint8
min: 0
max: 255


# Extract the red channel from the RGB image

In [5]:
print(rgb_image[:, :, 0])

[[255   0]
 [  0 255]]


# Demonstrate data types and arithmetic operations on bounded integers

In [6]:
a = np.array([250], dtype=np.float32)
b = np.array([10], dtype=np.float32)

result = a + b

print("a:", a)
print("b:", b)
print("result:", result)
print("result dtype:", result.dtype)

a: [250.]
b: [10.]
result: [260.]
result dtype: float32


dtype determines how numerical image values are represented, and arithmetic on bounded integer types can produce overflow.

# Create an image using arange and reshape

In [7]:
image = np.arange(20).reshape(4, 5)

print(image)
print(image.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


# Access a single pixel

In [8]:
pixel = image[2, 3]
print(pixel)

13


# Slicing rows, columns, and regions

In [9]:
row = image[1, :]
column = image[:, 2]
region = image[1:3, 1:4]

print(row)
print(column)
print(region)

[5 6 7 8 9]
[ 2  7 12 17]
[[ 6  7  8]
 [11 12 13]]


# Initialize an HWC image array

In [10]:
image_hwc = np.zeros((2, 3, 3), dtype=np.uint8)

image_hwc[:, :, 0] = 10
image_hwc[:, :, 1] = 50
image_hwc[:, :, 2] = 100

# Transpose HWC to CHW format

In [11]:
image_chw = np.transpose(image_hwc, (2, 0, 1))

# Print shapes after transposition

In [12]:
print(image_hwc.shape)
print(image_chw.shape)

(2, 3, 3)
(3, 2, 3)


# Verify array equality between HWC channel and CHW slice

In [13]:
np.array_equal(
    image_hwc[:, :, 0],
    image_chw[0, :, :]
)

True

# Exercise: Re-initialize HWC image

In [14]:
image_hwc = np.zeros((2, 3, 3), dtype=np.uint8)

image_hwc[:, :, 0] = 10
image_hwc[:, :, 1] = 50
image_hwc[:, :, 2] = 100

# Check exercise shape

In [15]:
image_hwc.shape

(2, 3, 3)